server:
  port: 8066 # Indicate the default PORT where this service will be started
  #ports: 8066:8091
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8066/eureka