server:
  port: 8091 # Indicate the default PORT where this service will be started
  ports: 8091:8091

eureka:
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
