ribbon:
    eureka:
        enabled: false

zuul:
    routes:
        input-kafka:
            url: http://localhost:8148/kv
        input-lemmatize:
            url: http://localhost:8140
        input-postag:
            url: http://localhost:8142
        input-tagger:
            url: http://localhost:8144
    host:
        socket-timeout-millis: 30000
#eureka:         #tells about the Eureka server details and its refresh time
#    instance:
#        leaseRenewalIntervalInSeconds: 1
#        leaseExpirationDurationInSeconds: 2
#    client:
#        serviceUrl:
#            defaultZone: http://127.0.0.1:8091/eureka/
#        healthcheck:
#            enabled: true
#        lease:
#            duration: 5
management:
    security:
        enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

spring:
    application:
        name: zuul-gateway