ribbon:
    eureka:
        enabled: false
server:
    port: 8081
zuul:
    routes:
        extractor-service:
            url: http://localhost:8094

#eureka:         #tells about the Eureka server details and its refresh time
#    instance:
#        leaseRenewalIntervalInSeconds: 1
#        leaseExpirationDurationInSeconds: 2
#    client:
#        serviceUrl:
#            defaultZone: http://127.0.0.1:8091/eureka/
#        healthcheck:
#            enabled: true
#        lease:
#            duration: 5
management:
    security:
        enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

spring:
    application:
        name: zuul-gateway