server:
    port: 8185
spring:
    data:
        mongodb:
            database: mydatabase
            port: 27017
            uri: mongodb://172.23.239.75/mydatabase

#
#        neo4j:
#            password: 123456
#            uri: bolt://localhost
#            username: neo4j