server:
    port: 8185
spring:
    application:
        name: query-engine
    data:
        mongodb:
            database: mydatabase
            port: 27017
            uri: mongodb://127.0.0.1/mydatabase

#tells about the Eureka server details and its refresh time
eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:8091/eureka/
    register-with-eureka: true
    fetch-registry: true

#
#        neo4j:
#            password: 123456
#            uri: bolt://localhost
#            username: neo4j
