server:
    port: 8067
#spring:
#    data:
#        neo4j:
#            password: 123456
#            uri: bolt://localhost
#            username: neo4j
#kafka:
#    port: localhost:9092
#management:
#    security:
#        enabled: false
#
