eureka:         #tells about the Eureka server details and its refresh time
    client:
        service-url:
            defaultZone: http://localhost:8066/eureka/
        register-with-eureka: true
        fetch-registry: true
server:
    port: 8888
management:
    security:
        enabled: false
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/arpitmishra02/config-server-repo.git
                        #/home/cgi/config-server-repo
                    #https://github.com/ShreelekhyaG/config-server-repo.git