#eureka:         #tells about the Eureka server details and its refresh time
#    client:
#        serviceUrl:
#            defaultZone: http://localhost:8066/eureka/
server:
    port: 8888
management:
    security:
        enabled: false
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/arpitmishra02/config-server-repo.git
                        #/home/cgi/config-server-repo
                    #https://github.com/ShreelekhyaG/config-server-repo.git
