server:
  port: 8100

kafka:
  port: localhost:9092

management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
spring:
  application:
    name: web-adaptor
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8091/eureka/
  register-with-eureka: true
  fetch-registry: true